### PR TITLE
More systematic README.md

### PR DESCRIPTION
**Pull request by hassanila**
Added Windows tutorial and cleaned it with links

### CODE REVIEW

**Comment by davidmann4** [comment]
hmm wrong project name and not sure if it is better ...

**Comment by hassanila97** [comment]
@davidmann4 Readme updated, please accept the pull request... you can check it out here: https://github.com/hassanila97/agario-feeder-bot/blob/master/README.md

**Comment by hassanila97** [comment]
@davidmann4 Readme updated, please accept the pull request... you can check it out here: https://github.com/hassanila97/agario-feeder-bot/blob/master/README.md

**Comment by hassanila** [comment]
@davidmann4 Readme updated, please accept the pull request... you can check it out here: https://github.com/hassanila97/agario-feeder-bot/blob/master/README.md

**Comment by hassanila97** [comment]
???????

**Comment by davidmann4** [comment]
This branch has conflicts that must be resolved

**Comment by hassanila97** [comment]
Can you tell me which conflicts?

**Comment by ItzLevvie** [comment]
Conflicts on README.md

**Comment by hassanila97** [comment]
Ok Now then...?

**Comment by ItzLevvie** [comment]
Now wait till david merges it.

**Comment by hassanila97** [comment]
@davidmann4 where r u???????

**Comment by hassanila97** [comment]
Bye

**Pull request closed without merging**
