### PR TITLE
Added bot counter. Fixed bot limit with actual spawn count.

### PR DESCRIPTION
**Pull request by gcsoftware**
Press F12 check console for bot count after feeder has started. Will implement visual overlay next.

### CODE REVIEW

**Comment by MasonBurdette** [comment]
This is great right here.  I have already implemented visual overlay, quite simple.  I'll show you the few lines of code to make it, when I get home.

**Comment by gcsoftware** [comment]
Thanks, feel free to submit a pull request with your overlay. Didn't have the time to implement the floating div with the counter.

**Comment by MasonBurdette** [comment]
I'm at school atm :P   Will do so, when I get home.

**Comment by makandz** [comment]
This is a nice update, but it would be better if it actually counted the number of ACTIVE bots instead of the number of bots. I got this on my server by having it add on +1 when the server has found the leader board, and -1 on Disconnect of the bot,

So that means if the bot doesn't spawn at all, it won't count :D

**Comment by gcsoftware** [comment]
Have you looked at the code? It pretty much does exactly that. Instead of on leaderboard update it increments on successful socket connection once it spawns in. Decrements on disconnect event. If anyone finds it more accurate to have it onLeaderboard it can easily be moved.

**Comment by makandz** [comment]
Wait what?

Oh lol, I don't know why my browser didn't load the rest of the code. Also, this is great right here. I see how it works now xD

Before I knew it didn't make much sense.

**Comment by davidmann4** [comment]
anyone tested this? looks huge!

**Comment by gcsoftware** [comment]
Sorry about that lol I'm still getting used to git. Could have had a lot less commits! Anyways I tested it myself and it works great. Anyone else want to confirm?

**Comment by SrNicolas** [comment]
Yep
Working like charms, gcsoftware contact me on skype please :nicolasdelito

**Comment by MasonBurdette** [comment]
+1

**Comment by SrNicolas** [comment]
@MasonBurdette contact me on skype please : nicolasdelito

**Comment by davidmann4** [comment]
many commits are much fun, see no issue there! was talking about the feature :+1:

**Pull request merged**
