### PR TITLE
Stop player cell on command

### PR DESCRIPTION
**Pull request by gcsoftware**
Added toggle movement for player cell. (Press D for Toggle Movement)
Disables both mouse click and mouse move.
Cleaned up key detection.

### CODE REVIEW

**Comment by davidmann4** [comment]
ohh nice - someone can test this ?

**Comment by makandz** [comment]
I'll test.

**Comment by makandz** [comment]
Update: It works just as said! Nice job!

But it would be nice if it stopped right on the spot and at the time you hit D. I see how this code is going, it goes to the mouse position you had while pressing D.

**Comment by mbm3** [comment]
+1, works as intended

**Comment by WebDevBG** [comment]
Not work for me..

**Comment by DeepSnowNeeL** [comment]
This is the code we use at agarbot.ovh : 

```
function hey(buf,x,y){
            if(stopMove){
                var midX=0;
                var midY=0;
                var minX =0;
                var minY =0;
                var maxX = 0;
                var maxY = 0;
                for(index in l){
                    var ball = l[index];
                    if(index == 0){
                        maxX = ball.x;
                        minX = ball.x;
                        maxY = ball.y;
                        minY = ball.y;
                    }else{
                        maxX = Math.max(maxX,ball.x);
                        minX = Math.min(minX,ball.x);
                        maxY = Math.max(maxY,ball.y);
                        minY = Math.min(minY,ball.y);
                    }
                }
                midX = (minX+maxX)/2;
                midY = (minY+maxY)/2;

                buf.setInt32(1, midX, !0);
                buf.setInt32(5, midY, !0);
                buf.setUint32(9, 0, !0);
                sendBuffer(buf);
            }
            else{
                buf.setInt32(1, x, !0);
                buf.setInt32(5, y, !0);
                buf.setUint32(9, 0, !0);
                sendBuffer(buf);
            }

        };
```

:)

**Comment by mbm3** [comment]
@DeepSnowNeeL thats for stopping bots.  we're talking about stopping the player's cell.

**Comment by DeepSnowNeeL** [comment]
Oops I thought this was the PR for the stop bot feature :p

Le mer. 10 févr. 2016 à 16:15, Mason Burdette notifications@github.com a
écrit :

**Comment by mbm3** [comment]
@DeepSnowNeeL feel free to edit this script, and make a pull request for that feature.  the more people contribute, the better!

(Totally Unrelated)
@DeepSnowNeeL how'd you do the fb tokens for each bot?  was it like this.auth_token = token.bot_id?
i already know you have a lot of fb accounts.

**Comment by davidmann4** [comment]
anyone should alter the README.md

**Comment by mbm3** [comment]
@davidmann4 will do so later.

**Comment by WJKH** [comment]
@MastaCoder +1

Also mouse movement shouldn't disable it because if you move the mouse to control bots then the ball will move again.

**Pull request merged**
