### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by Lukkez**

### CODE REVIEW

**Comment by davidmann4** [comment]
puh anyone tested ?

**Comment by Lukkez** [comment]
I tested, work normal, only remove lines and put as @require

**Comment by hassanila** [comment]
@Lukkez Yes it will work but you're hosting the script on your github now... and you can change it to anything... It might even be malicious code... you never know.... so it's your choice @davidmann4

**Comment by Lukkez** [comment]
Rlly?
Click on the link
It's the code from //EXPOSED CODE BELOW

**Comment by Lukkez** [comment]
image

**Comment by hassanila** [comment]
@Lukkez  I know, what I'm saying is that you can replace that code whenever you want lol....   Not towards you specifically... jsut saying it as a safety measure

**Comment by WJKH** [comment]
> @Lukkez Yes it will work but you're hosting the script on your github now... and you can change it to anything... It might even be malicious code... you never know.... so it's your choice @davidmann4

He's not hosting the script, another user host it.
He can change the code and it's risky, maybe @davidmann4 could host it or if you don't trust others just host it yourself and remplace one line of the userscript.

Host and merge :+1:

**Comment by Lukkez** [comment]
I don't know much about pull requests this is the fukin reason, my friend is a coder and he use this link for his script

**Comment by Lukkez** [comment]
I not more want this, i will close and i'm only helping

**Comment by davidmann4** [comment]
not a big fan of the idea anyways ..

**Pull request closed without merging**
