### PR TITLE
Added Toggle Bot Following, Player cell retrieval, and small fixes.

### PR DESCRIPTION
**Pull request by gcsoftware**
-Added Toggle for Bot following (Move to mouse or Move to player cell) (Press A to toggle)
-Player Cell can now be accessed using function getCell()
-Added fix for respecting bot max limit
-Changed stop movement event to onmousemove instead of onmousedown event.

Should take care of #159 & #161..

### CODE REVIEW

**Comment by WJKH** [comment]
@gcsoftware nice contributions, thanks!

I believe the stop movement should stop cell at cell position and not mouse position, also mouse move shouldn't enable the movement again. This should work in this way: press key disable movement, press key enable movement.

I will test this update at the night.

**Comment by gcsoftware** [comment]
@WJKH The enable/disable toggle is controlled by pressing the D key. Mouse Movement does not control the toggle in any way. I would love to have instant stop at the current position, but it's difficult to pull off. I was able to do it in my tests, but it came with a negative side effect where your cell would drift endlessly into the last direction.

**Comment by davidmann4** [comment]
sounds great! someone can test?

**Comment by gcsoftware** [comment]
@davidmann4 Once this is merged in, I have the new commits ready to pull and fix #165

**Comment by WJKH** [comment]
@gcsoftware I haven't tested this last update but in the update https://github.com/davidmann4/agario-feeder-bot/pull/154 if you move the mouse the cell continue moving.

**Comment by davidmann4** [comment]
puh, anyone tested this?

**Comment by davidmann4** [comment]
just merged it in without testing :+1:

**Comment by gcsoftware** [comment]
Well if any issues arise we can take care of it :sweat_smile:

**Comment by WJKH** [comment]
@gcsoftware I have tested this last version recently and the issue with the mouse move disabling stop movement function persist.

Also some new issues found:

Bot Count: [object Object]
And when I press D (stop movement): Uncaught TypeError: canvas.onmousemove is not a function

**Comment by gcsoftware** [comment]
@WJKH I have tested the latest and cannot reproduce this issue with the stop movement. Bot Count also is working fine here. Are you playing on a private server?

**Comment by WJKH** [comment]
@gcsoftware no, I'm playing on public servers.

**EDIT:**

The stop movement issue is related to another script, the mini-map server script to be right. If the mini-map script is disabled it's working properly.

The bot count issue haven't checked yet, but I'm running four process to handle more bots without CPU issues and lag.

BTW... I was trying to get Agarplus working with feeder userscript without sucess and now I have this issue with the mini-map script, is there any way to get both script working?

**Pull request merged**
