### PR TITLE
Simple Stop bots function

### PR DESCRIPTION
**Pull request by SrNicolas**
Make the feeder crash for stopping bots
from the agar.io tab

### CODE REVIEW

**Comment by mayed505** [comment]
Nice Dude.

**Comment by WJKH** [comment]
I believe there's a better way to start/stop feeder on user request.
BTW.. Q key is used in Agar.io to change spectator view. use another key.

**Comment by Petterholm** [comment]
https://gyazo.com/cee9e70c0c9d713069343ec08f0aa756

**Comment by philw1508** [comment]
@Petterholm  There was a new agario update!! there are more skins available etc... so mine is not working too :((

**Comment by davidmann4** [comment]
merge conflict

**Comment by zettabyte918** [comment]
[ReferenceError: exit is not defined]

**Pull request closed without merging**
