### PR TITLE
Updated a lot of wording and style of script

### PR DESCRIPTION
**Pull request by makandz**
I cleaned up most of the code and reworded it to make more sense to new people :+1:

### CODE REVIEW

**Comment by makandz** [comment]
I will also update the readme later tonight or this week if I have time :)

**Comment by davidmann4** [comment]
cool stuff! will review it tomorrow!

**Comment by makandz** [comment]
Alright :+1:

**Comment by davidmann4** [comment]
added a few comments - maybe you change this things in the future - merging it for now

**Pull request merged**
