### PR TITLE
Remove unnecessary (AGAIN)

### PR DESCRIPTION
**Pull request by Lukkez**
About security, don't have nothing, all my friends use this code to don't need to put much lines on the code, it's only to delete some lines :)

### CODE REVIEW

**Comment by mayed505** [comment]
Why do we all need to remove the " unnecessary " code?
since you are adding? https://raw.githubusercontent.com/xzfc/agar-expose/master/expose.user.js
Its kinda useless right now.

**Comment by Lukkez** [comment]
Because remove arround 100 lines, and make more easy to find some code for me

**Comment by Lukkez** [comment]
If don't want only not put
Is only a suggestion

**Comment by hassanila97** [comment]
@Lukkez You're 100% right, we can remove 100 lines here, but that's not all...  We now get immediate updates that are made to agar-expose as the script is coming directly from the original repo...

-------------

@davidmann4 Please reopen this pull request and think about integrating it.... as I alredy said above it's just positive to have it coming directly from the origin and not have it integrated in this repo... PLZ JUST DO IT   :+1:

**Comment by hassanila** [comment]
@Lukkez You're 100% right, we can remove 322 lines and add 1 single line 2016-03-01 10_31_43-remove unnecessary again by lukkez pull request 248 davidmann4_ogar-feede
 here, but that's not all...  We now get immediate updates that are made to agar-expose as the script is coming directly from the original repo...
Meaning that now every single update to the agar-expose script gets automatically integrated in this...

---

@davidmann4 Please reopen this pull request and think about integrating it, this will never and can never cause any errors.... as I already said above it's just positive to have it coming directly from the origin and not have it integrated in this repo... PLZ JUST DO IT   :+1:    Who thinks like me? Plz leave a comment below :P

**Comment by mayed505** [comment]
@hassanila97  i totally agree with your and @davidmann4 should add this :+1:

**Pull request closed without merging**
