### PR TITLE
Updated agar-expose to fix hook cellColor

### LINKED ISSUE #224: Console error (Userscript)
I keep getting this error in console and can't edit the userscript...
2016-02-21 21_07_12-agar io

### PR DESCRIPTION
**Pull request by gcsoftware**
Fixes #224. Implements #182.

### CODE REVIEW

**Comment by hassanila97** [comment]
Sry bro but, for me the console is full of errors and it doesn't work...

**Comment by gcsoftware** [comment]
@hassanila97 Can't reproduce those errors. Working fine over here. https://gyazo.com/9825918b12bcebef410e7a927cf7c9d0

**Comment by hassanila97** [comment]
@gcsoftware Well there are some syntax errors as I can see in your console that must be fixed.... they are in Davids userscript and I'm using Chrome.... Other users have also reported the same issue in Skype chat.... like 4+ people  so it's not just me....   Also why aren't there semicolons, @davidmann4 ?

**Comment by davidmann4** [comment]
dunno, add them?

**Comment by davidmann4** [comment]
merge or not to merge?

**Comment by hassanila** [comment]
@davidmann4 they are hundreds+ so... humanly impossible...  It is also a downside to not have semicolons... you cannot then minify the userscript .....  Dont know.... just wait maybe tmrrow

**Comment by davidmann4** [comment]
puh - code look good, MERGED!

**Pull request merged**
