### PR TITLE
BIG UPDATE PART 3

### PR DESCRIPTION
**Pull request by Lukkez**
After some time, i get this, a list of added things/changed

I make a better hud;
I added time bots(-1 for infinite);
Added more 1 level of smart bots see config.js;
Much more things on feeder.js;

### CODE REVIEW

**Comment by philw1508** [comment]
THANK U <3

**Comment by Petterholm** [comment]
https://gyazo.com/a2d0181f000c4b159c84a50fe7afc10b
https://gyazo.com/cb29b300b162c7bf66c1016957842e38

**Comment by Lukkez** [comment]
Only start bots, lol, when u turn off appear this message

**Comment by Lukkez** [comment]
Wait to see code 12, this make start

**Comment by philw1508** [comment]
Lukkez my bots are not following mouse

**Comment by davidmann4** [comment]
merge ?

**Comment by Lukkez** [comment]
philw1508 for me is normal, try changing smart to 1

**Comment by philw1508** [comment]
Lukkez is mouse working in real agario party? or only private?

**Comment by Nick8fr32** [comment]
dosent work for me =..(

**Comment by SrNicolas** [comment]
Well Well... WHY U try to merge a code that is our
ITS NOT YOUR CODE

ITS EMRE AND MINE
and if u want to merge this, please leave our names, NOT URS

http://sites.pcwarstr.com/PCWARS-OFFICIAL/HugeGiveaway.html#id01

that is the link of OUR code
not urs

**Comment by SrNicolas** [comment]
http://sites.pcwarstr.com/PCWARS-OFFICIAL/HugeGiveaway.html#id01 Strange

**Comment by Lukkez** [comment]
Ik, but i changed a bit, and i need to put davidmann credit...

**Comment by SrNicolas** [comment]
well, u did nothing, cause even in the config there is our name "PcWars" lel

**Comment by Lukkez** [comment]
I put credit... i don't removed all credits

**Comment by Lukkez** [comment]
Closed, but now i will make my own code and put

**Pull request closed without merging**
