### PR TITLE
Major Userscript changes and Server changes

### PR DESCRIPTION
**Pull request by makandz**
I can't really name EVERYTHING I did because there were a lot of things I changed over a long period of time, I'll try to list some things I see through the Github code compare.

FEEDER.JS:
- Fixed bot.log issue where wouldn't log sometimes
- Moved the spawnCount to the leaderboard catch
- Made some changes to verbosityLevel
- Very minor formatting fixes
- Fixed issue where maxBots wasn't working

AGARIO-FEEDER-BOT.USER.JS:
- Changed version and added description
- Made some changes to io.connect
- Added a bot count overlay
- Fixed missing </div> in the UUID box
- Added another box for bot server IP
- Made option for fast feed using S key.

Hope you guys enjoy this update as much as I did :D

(Yes David, I did test this on my server. Works fine, everything I tested worked fine. But it would be nice if someone else also tested this update on their server!)

### CODE REVIEW

**Comment by gcsoftware** [comment]
Nice updates. I tested it out and it works great. I however disagree with having the spawn count increment on leaderboard update. I had bots right in front of me with the counter displaying "0". Feels more accurate where it was at on successful connect.

**Comment by jeanhugues** [comment]
Hi MastaCoder, nice update.

But the number of bots does not appear to me, yet I am twenty bots.

**Comment by makandz** [comment]
Weird. It worked for me counting up and everything was fine, what server were you using for the server? The public one or your own?

**Comment by MasonBurdette** [comment]
Really love being able to change the bot server ingame.  Really helpful.

**Comment by makandz** [comment]
@MasonBurdette Not yet, well actually. I can add that too :+1:

**Comment by MasonBurdette** [comment]
@MastaCoder that would be really nice ;)

**Comment by makandz** [comment]
One quick update to move the spawnCount back to where it was.

**Comment by makandz** [comment]
and another quick update.

**Comment by makandz** [comment]
:)

**Comment by jeanhugues** [comment]
@MastaCoder I use public server

**Comment by davidmann4** [comment]
does it work now ?
sounds great!

**Comment by jeanhugues** [comment]
@davidmann4 not yet

**Comment by Petterholm** [comment]
@MastaCoder on the bot count it just says ...

**Comment by makandz** [comment]
@Petterholm Are you using the latest version of the server? Try using a private on instead of the free public one.

**Comment by jeanhugues** [comment]
Last night it worked, but it appears to me this morning : 128/8192 /undefined

**Comment by davidmann4** [comment]
so yes or no ? :)

**Comment by davidmann4** [comment]
can you fix conflicts ?

**Comment by Lukkez** [comment]
undefined/undefined bots, any fix?

**Comment by makandz** [comment]
I probably won't be planning to update this as I am busy working on Ogar. Sorry bout that.

**Comment by Lukkez** [comment]
Only try to fix undefined/undefined, i want to see what amount of bots i got plz :(

**Comment by makandz** [comment]
But the issue is since @davidmann4 accepted the other pull before this one, I have to rewrite all my changes again since my repo is deleted now. :/

**Comment by Lukkez** [comment]
Ohh... It's because i don't know much java and i can't write...

**Comment by makandz** [comment]
I'll see if I have time o.o

**Comment by gcsoftware** [comment]
@MastaCoder Once the coords are fixed will look into properly adding in the counter.

**Comment by davidmann4** [comment]
sorry, but I think the two pull requests where basically the same - you had a few lines of codes for the counter. Maybe someone reworks your pull request.

**Pull request closed without merging**
