### PR TITLE
Update names.js

### PR DESCRIPTION
**Pull request by iNewLegend**
Add "Israel".

### CODE REVIEW

**Comment by davidmann4** [comment]
image

this name has no skin?

**Comment by iNewLegend** [comment]
:(

**Comment by davidmann4** [comment]
the default names only contain skin names, however there is a cvonfig to set all bots to a specific name

**Comment by davidmann4** [comment]
https://github.com/davidmann4/agario-feeder-bot/blob/master/config.sample.js#L24

**Pull request closed without merging**
