### PR TITLE
Show number of bots actually playing

### PR DESCRIPTION
**Pull request by makandz**
Well I made this quickly this morning because I have it custom on my server and thought I would share it!

Basically, if you have verbosity set to 1 or higher, it will show a number everytime a bot connects to a game, and when they disconnect, It shows the number of actually alive bots. This is the exact code on my server, so I don't think it should have any issues. If anyone else is good at socket.io and can transmit this to the server, go ahead.

Also to note, I removed the pewdiepie name from name.js because it doesn't have a skin anymore.

### CODE REVIEW

**Comment by WebDevBG** [comment]
It's good idea..i need this script.. :)

**Comment by davidmann4** [comment]
anyone tested it ?

**Comment by WJKH** [comment]
pewdiepie = army skin if you are logged to FB

**Comment by MasonBurdette** [comment]
@WJKH screenshot? (doesnt work for me :P)

**Comment by WJKH** [comment]
@MasonBurdette you're right, they removed it in the last days.

**Comment by makandz** [comment]
@davidmann4 I tested this and it worked on my server, maybe someone else also test ;D

**Comment by gcsoftware** [comment]
@MastaCoder The skin thing I agree, but isn't this a bit redundant? It pretty much does the same thing as #143. I could just move the increment counter to leaderboard?

**Comment by makandz** [comment]
@gcsoftware I just remembered your code was there. I'll update everything again and push out a pull request :+1:

**Pull request closed without merging**
