### PR TITLE
Mouse following in Blind mode.

### PR DESCRIPTION
**Pull request by xa**
Broke custom bot names, cell recognition should be by cell_id not name.

### CODE REVIEW

**Comment by hassanila97** [comment]
Nice, but you could add a key to press to switch from mouse to cell and viceversa.. easy..

**Comment by Lukkez** [comment]
This make the bots like www.raga.pw bots? if yea, i will make a pull request later for some shortcuts/better ui

**Comment by hassanila** [comment]
IT makes it like it... but only when bots are in range

**Comment by Lukkez** [comment]
I'ma use this, can i use with public feeder?

**Comment by xa** [comment]
You need to run your own feeder server with nodejs.

**Comment by mayed505** [comment]
@kcxx i have problems bots spawn only 4~10 with 1K socks5 proxies but with david's they spawn 500.
- if they join they dont follow me.  (with my feeder)

**Comment by hassanila97** [comment]
@Mayed Read my comment... this is vased on old version so it will crash somethings

**Comment by mayed505** [comment]
@hassanila97 what do u mean? when i first launched it  it worked for a few secs and then stopped

**Comment by mayed505** [comment]
@ it works perfectly on ogar....

**Comment by davidmann4** [comment]
what exactly will crash?

**Comment by hassanila97** [comment]
@davidmann4 It's like you updated some code a while ago... and now if you merge this script all those updates are gone... you understand  (**They're not so many btw**)

**Comment by hassanila97** [comment]
@davidmann4 e updated it so now I think nothing will crash... no problem... sry

**Comment by xa** [comment]
mv is the vector that bot should move.

**Comment by xa** [comment]
Also you can press 'a' to change from mouse movement to cell movement

**Comment by davidmann4** [comment]
!? still do not get MV - I guess there are way better solutions to do this. Like offset calculation and overriding mode to normal for bots who know the offset

**Comment by mayed505** [comment]
@kcxx   @hassanila97 
now the bots doesnt follow even in blind mode so as david's one.
even in Ogar doesnt follow --__--

**Comment by xa** [comment]
It's not my fault that you can't use software properly --__--

http://gfycat.com/PoorSlightAsianelephant

**Comment by mayed505** [comment]
@kcxx can you help me fix it?

**Comment by mayed505** [comment]
@kcxx  your ARE THE POORKCXXASIANELEPHANT BITCH

**Comment by philw1508** [comment]
my bots arent moving although i have my own server :(  and why do the bots only show numbers on it?

**Comment by xa** [comment]
@mayed505 Stop acting like a spoiled kid. Noone is going to help you that way.

**Comment by mayed505** [comment]
Well u called me. Poorslightasianelephant......

**Comment by ItzLevvie** [comment]
@mayed505 He didn't call you that, It's a random generated string.

**Comment by WJKH** [comment]
LMAO

**Comment by hassanila97** [comment]
Where dfq is David.....  ---___---  som1 else needs to help David and also have write access... ☆___☆

**Comment by mayed505** [comment]
@ItzLevvie  no.....

**Comment by davidmann4** [comment]
everyone can use this quickfix - i will not merge it since it is not well coded - as far as I understood it you added a new packet called MV - I do not undertsand why we need this

**Comment by xa** [comment]
@davidmann4 Yeah it was more like a quick hack, not something to be used for production code.

**Comment by ItzLevvie** [comment]
@mayed505 It's a random generated string....

**Comment by Petterholm** [comment]
Do the bots follow you in public?

**Comment by Lukkez** [comment]
Someone can do a name generator for bots? like bagar.io, because i know a ogar server who have anti bots with much same names

**Comment by mayed505** [comment]
@Lukkez http://textmechanic.com/text-tools/randomization-tools/random-string-generator/
just add ur prefix

**Comment by Lukkez** [comment]
Lol, much good

**Comment by philw1508** [comment]
@kcxx  After the update my bots arent moving anymore

**Comment by rafailrafail** [comment]
bots not follow me...

**Comment by philw1508** [comment]
U have to use agar expose

**Comment by rafailrafail** [comment]
link?

**Comment by davidmann4** [comment]
merge conflict

**Comment by rafailrafail** [comment]
david can you send me the link?

**Comment by rafailrafail** [comment]
@davidmann4 can you upload a new tutorial video??

**Pull request closed without merging**
